# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hedilakhdhar.github.io/nbdev_bot/"

git_url = "https://github.com/hedilakhdhar/nbdev_bot/tree/master/"

def custom_doc_links(name): return None
