# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"thread_decor": "00_deribit_interface.ipynb",
         "Deribit": "00_deribit_interface.ipynb",
         "AMOUNT_TO_TRADE": "01_market-maker.ipynb",
         "INSTRUMENT_NAME": "01_market-maker.ipynb",
         "CLIENT_ID": "01_market-maker.ipynb",
         "CLIENT_SECRET": "01_market-maker.ipynb",
         "deribit": "01_market-maker.ipynb",
         "logwritter": "01_market-maker.ipynb",
         "first_trade": "01_market-maker.ipynb",
         "step_in_algo": "01_market-maker.ipynb",
         "First_setuper": "01_market-maker.ipynb",
         "Order_manager": "01_market-maker.ipynb"}

modules = ["interface/deribit_interface.py",
           "market-maker.py"]

doc_url = "https://hedilakhdhar.github.io/nbdev_bot/"

git_url = "https://github.com/hedilakhdhar/nbdev_bot/tree/master/"

def custom_doc_links(name): return None
